<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Base\**" />
    <Compile Remove="Interfaces\**" />
    <Compile Remove="Model\**" />
    <EmbeddedResource Remove="Base\**" />
    <EmbeddedResource Remove="Interfaces\**" />
    <EmbeddedResource Remove="Model\**" />
    <None Remove="Base\**" />
    <None Remove="Interfaces\**" />
    <None Remove="Model\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.0" />
    <PackageReference Include="BlazorForms" Version="2.0.4" />
  </ItemGroup>

  <ItemGroup>
    <!--<ProjectReference Include="..\..\shared\BlazorForms.Shared\BlazorForms.Shared.csproj" />-->
  </ItemGroup>

</Project>
