version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-CU14-ubuntu-22.04
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrong!Passw0rd"
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql

volumes:
  sqlserverdata:
    